### ISSUE TITLE
Failed to acquire output duplication

### ISSUE THREAD

**Issue by animerqi** [ideless/yas-lock#13]
![image](https://user-images.githubusercontent.com/84447025/195624831-7b3d7d9b-d81b-48c7-ab1f-3870f9574bf7.png)

**Comment by ideless** [comment]
试试[v1.0.8](https://github.com/ideless/yas-lock/releases/tag/v1.0.8)

**Comment by upkimo** [comment]
还是不行，用的就是v1.0.8

**Comment by Lanyuxxx** [comment]
> 还是不行，用的就是v1.0.8

同样使用v1.0.8出现这个问题

**Comment by ideless** [comment]
试试 [yas-lock_v1.0.8-beta3](https://github.com/ideless/yas-lock/releases/download/v1.0.8/yas-lock_v1.0.8-beta3.exe)

**Comment by upkimo** [comment]
> 

之前1.0.8用不了我就用了之前的1.0.5就发现可以了。现测试这个1.0.8-beta2也是可以用的
