### ISSUE TITLE
每次解锁在第七页连跳两个不解锁的概率大

### ISSUE THREAD

**Issue by genself** [ideless/yas-lock#16]
1.经过多次使用在一千多个里对七百多个圣遗物批量加解锁，发现每次解锁在第七页连跳两个不解锁的概率大，一次加/解锁大概有一到四个漏，有一次出现三个没被解锁到即第七页有两个被跳过了没解锁和第三十页（如果没数错的话）有一个被跳过没解锁的情况存在。也就是第241到第280，还有第1161到第1200（如果这第三十页没数错的话）。
2.尝试过 --scroll-stop 1500的方法，翻页慢了但还是会漏。解锁可以扫两遍来实现全部解锁，但是加锁漏了在一千多个里很难排除出漏哪个。
3.发现加锁漏了是因为加锁前记录了要加锁的圣遗物的数量，然后在全部五星已解锁的情况下进行加锁，完毕后再扫一遍进网页导入发现加锁的数量对不上。
4.这边硬件情况是电脑用十几元的无线网卡连手机的热点，游戏和系统在固态上。
![屏幕截图(466)(1)](https://user-images.githubusercontent.com/101165579/200238876-453f3759-63f4-482f-b864-1ed67b68870f.png)
![屏幕截图(458)(1)](https://user-images.githubusercontent.com/101165579/200238889-2f6ea296-1a01-4d4f-9911-8e0300603ab4.png)
![屏幕截图(463)(1)](https://user-images.githubusercontent.com/101165579/200238894-67c0157f-1b1c-4e81-897b-7e23c6696037.png)
![屏幕截图(465)(1)](https://user-images.githubusercontent.com/101165579/200238899-3c9e5ad3-48b7-40aa-9efe-3c60a088431c.png)

**Comment by genself** [comment]
检查了下，加锁也是容易在第七页跳过两个圣遗物
![02](https://user-images.githubusercontent.com/101165579/200256862-f799c478-03e0-4cc5-8a7f-95cbb5b293bc.jpg)

**Comment by ideless** [comment]
试试[beta版](https://github.com/ideless/yas-lock/releases/download/v1.0.8/yas-lock_v1.0.8-beta3.exe)

**Comment by genself** [comment]
用beta版解锁两三次没发现问题。加锁试了两次，第一次漏一个没找漏哪个，第二次也漏一个，通过对比文档发现漏了1194，即第30页最下面一行其中一个

**Comment by ideless** [comment]
试试[beta4](https://github.com/ideless/yas-lock/releases/download/v1.0.8/yas-lock_v1.0.8-beta4.exe)，加上如下选项
```
--lock-stop 500
```
即落锁后等待500毫秒

**Comment by genself** [comment]
感谢大佬，[beta4](https://github.com/ideless/yas-lock/releases/download/v1.0.8/yas-lock_v1.0.8-beta4.exe)很稳
