### ISSUE TITLE
min-level 命令行参数失效？

### ISSUE THREAD

**Issue by HeroTch** [ideless/yas-lock#19]
![图片](https://user-images.githubusercontent.com/29833444/206775403-a1dffb79-7d0e-4648-8860-5a13b22f8e87.png)
设定min-level参数为20，但读取到20级以下圣遗物时没有停止扫描
![图片](https://user-images.githubusercontent.com/29833444/206775226-f30f0921-bed8-4fbc-baeb-9f622e735a95.png)
1.0.8beta6版

**Comment by HeroTch** [comment]
还有，good.json里没有将重复的圣遗物给剔除，mona.json是剔除了的

**Comment by ideless** [comment]
扫描和识别是两个线程，目前min-level是全部扫描并识别完再筛选。可以按鼠标右键提前终止。
重复扫描有点奇怪，麻烦下最新的beta版加`--verbose`再试一下

**Comment by HeroTch** [comment]
> 扫描和识别是两个线程，目前min-level是全部扫描并识别完再筛选。可以按鼠标右键提前终止。 重复扫描有点奇怪，麻烦下最新的beta版加`--verbose`再试一下

抱歉，邮件漏看了，beta9已经不会再重复了，min-level参数在 --help 里和 README 里说明一下吧，比较不容易想到
