### ISSUE TITLE
Wireshark/ pcap文件抓包后导入 没有圣遗物

### ISSUE THREAD

**Issue by qwuae1** [ideless/yas-lock#2]
不知道是不是海外用户 连 国服有延迟
抓包抓到东西了，可是网站导入没有显示圣遗物
导入网站console有log了...
![image](https://user-images.githubusercontent.com/36930393/178085465-dd28a168-ece7-494a-b21a-3fb0067732fc.png)

试了下抓到完全进游戏也一样
奇了怪了

我把pcap文件直接传给你？

**Comment by ideless** [comment]
确实很奇怪，你可以发我邮箱，pyjy@yahoo.com，如果你相信我的话

**Comment by qwuae1** [comment]
已发

**Comment by ideless** [comment]
> 已发

分享链接没有访问权限

**Comment by ideless** [comment]
done

**Comment by qwuae1** [comment]
谢谢~
顺便是什么问题嘛
感觉就是验证header长度的时候fail了，我的header是14位，不是16位？
海外用户还能长度不一样么
hhh自己debug完全不知道发生了什么

**Comment by ideless** [comment]
pcap文件里面有一些冗余数据我没有处理   On Sunday, July 10, 2022 at 06:11:18 AM GMT+8, QIXIAN WU ***@***.***> wrote:  
 
 


谢谢~
顺便是什么问题嘛
header里面的长度，int 16 读的不太对？hhh自己debug完全不知道发生了什么
