### ISSUE TITLE
无法识别乐园套

### ISSUE THREAD

**Issue by TomoeMami** [ideless/yas-lock#20]
![图片](https://user-images.githubusercontent.com/16950305/208129403-7f96a4bd-25b2-4763-bd53-0ebfe3dc6a00.png)

**Comment by ideless** [comment]
下最新的beta版

**Comment by wang-hui** [comment]
同样的问题，最新的[yas-lock_v1.0.8-beta8.exe](https://github.com/ideless/yas-lock/releases/download/v1.0.8/yas-lock_v1.0.8-beta8.exe) 大量识别出错

**Comment by ideless** [comment]
试试beta9
