### ISSUE TITLE
云原神显示“不支持的分辨率”如何调整

### ISSUE THREAD

**Issue by pray-753391** [ideless/yas-lock#21]
--help里没有告诉我如果设置云原神的话还需要额外设置其它哪些选项
![image](https://user-images.githubusercontent.com/66723274/208852164-4243abd7-5fb6-4773-8460-4364ab1be0fd.png)
如果只按更新里面的设置参数的话会显示“不支持的分辨率”
![EQ`_A7((7J%M0 ``AO2)JCO](https://user-images.githubusercontent.com/66723274/208852314-3df514c7-48b8-42f0-8b6c-8b29b9daef7d.png)

**Comment by ideless** [comment]
云原神设置成1600*900
