### ISSUE TITLE
意外的WARN

### ISSUE THREAD

**Issue by CUZNIL** [ideless/yas-lock#22]
不影响使用，但是似乎未正确识别主词条。
![image](https://user-images.githubusercontent.com/76582404/209834300-be47c4b1-42bd-4d3c-b0f5-ce65a95e4cf5.png)

**Comment by ideless** [comment]
不是主词条识别错误，是检测到了重复圣遗物，如果实际上没有重复的话考虑降低速度，比如`--speed 4`

**Comment by CUZNIL** [comment]
懂了
