### ISSUE TITLE
更新后圣遗物适配率大幅下降

### ISSUE THREAD

**Issue by kaminokyoku** [ideless/yas-lock#24]
0级冰本羽毛双爆四属性，神里的适配率只有16.2%，明显不合理，在更新前要高多了

**Comment by ideless** [comment]
我没有改过算法。可能和你想的不一样，算的是适配概率：

> 圣遗物a对角色c的适配概率定义为，刷100个满级圣遗物，其中和a同部位同主词条的圣遗物得分均不超过a的满级期望得分的概率。如果a对c是散件则是200个。

哪怕是双爆胚子，适配概率也可能天差地别（从3%到100%）。你的羽毛是100个随机冰套圣遗物中的最优选的概率只有
16.2%，这是完全有可能的。

**Comment by kaminokyoku** [comment]
谢谢回复！那可能是我用了自定义配装导致的
