### ISSUE TITLE
固定几个圣遗物总是扫描出错

### ISSUE THREAD

**Issue by hcy0317** [ideless/yas-lock#25]
![image](https://user-images.githubusercontent.com/37647679/210842245-82addd65-f57b-46c5-96c4-ebd7c8cf8d90.png)
不知道为啥，都是物伤杯
另外筛选过后最后一页总是 出现翻页问题
![image](https://user-images.githubusercontent.com/37647679/210845358-b9923d46-c5cd-4610-9684-222803c0b1a1.png)

**Comment by hcy0317** [comment]
a卡锐化的锅

**Comment by huojieren** [comment]
我去我也是这样，想了一晚上，因为另一台电脑就不会，很好奇你是怎么发现的啊

**Comment by hcy0317** [comment]
> 我去我也是这样，想了一晚上，因为另一台电脑就不会，很好奇你是怎么发现的啊

啊。因为略微思考了下这种只有特定字符出错的原因：1.识别模型问题；2.输入的画面问题。然后就想到了超分辨率以及锐化会改变字符的像素特征，然后就去试了下，结果就好了。另外那个翻页问题也是想了下可能的判断条件，最后发现留一个非4星圣遗物就可以完美解决问题。总之就是排除法啦
