### ISSUE TITLE
运行加锁的操作不是幂等的

### ISSUE THREAD

**Issue by LeiShi1313** [ideless/yas-lock#26]
远行加锁操作是没有判断圣遗物是否已经加锁，如果已经加锁会反而解锁。希望在加锁操作时做判断圣遗物是否已经上锁，从而让加锁操作幂等

**Comment by ideless** [comment]
原本做的就不是“加锁“，而是”翻转锁的状态“，至于翻转哪些目前完全由使用者自己负责。为什么需要重复运行多次呢？

**Comment by ideless** [comment]
[v1.0.9-beta1](https://github.com/ideless/yas-lock/releases/download/v1.0.9/yas-lock_v1.0.9-beta1.exe) 支持新的lock.json的格式：
```rust
struct LockValidationRecord {
    index: u32,
    locked: bool,
}

struct LockFormatV2 {
    version: u32,
    flip_indices: Vec<u32>,
    lock_indices: Vec<u32>,
    unlock_indices: Vec<u32>,
    validation: Vec<LockValidationRecord>,
}
```
[source](https://github.com/ideless/yas-lock/blob/main/src/lock/mod.rs)

**Comment by LeiShi1313** [comment]
因为“加解锁”依据的文件叫`lock.json`而不是`flip.json`
