### ISSUE TITLE
在加锁阶段显示错误：指标超出范围

### ISSUE THREAD

**Issue by shuishiwojiade** [ideless/yas-lock#29]
对圣遗物加锁的时候，如图所示的运行过程：
<img width="720" alt="Snipaste_2023-01-27_15-30-07" src="https://user-images.githubusercontent.com/23050341/215032295-28ed999f-a238-4b28-aabb-f81a837a11f8.png">

**Comment by ideless** [comment]
看一下lock.json的内容
