### ISSUE TITLE
无法使用 启动后不会扫圣遗物

### ISSUE THREAD

**Issue by Mikoto-qiuhua** [ideless/yas-lock#32]
![image](https://user-images.githubusercontent.com/102891248/219948668-96a5f9da-96ff-4213-99f9-49a024b683e9.png)

**Comment by ideless** [comment]
调成1600*900试试

**Comment by Mikoto-qiuhua** [comment]
> 调成1600*900试试

不行 他鼠标移动到第一个圣遗物框框左边 没在框内 就停止了
![image](https://user-images.githubusercontent.com/102891248/219955655-c802405e-f435-4828-9d50-0a032788974a.png)

**Comment by ideless** [comment]
你的背包界面不对，正常应该是一行8个

看一下issue #15
