### ISSUE TITLE
扫描时初始扫描速度过于快了，可能是识别出重复的圣遗物的原因

### ISSUE THREAD

**Issue by HeroTch** [ideless/yas-lock#33]
重复识别在不加参数运行时可以稳定复现，降低 --speed 可以避免
![图片](https://user-images.githubusercontent.com/29833444/219961936-1bf1af4b-4a5b-4b9b-a8eb-c29cca858fd6.png)
之前修复过了，现在好像又出现了

**Comment by ideless** [comment]
第一个就重复？加`--verbose`看一下

**Comment by HeroTch** [comment]
来了，我的电脑开了一堆程序之后出现次数就少了，加了--verbose速度也会降低，不会出现dup了
