### ISSUE TITLE
解锁圣遗物显示invalid type: map, expected a sequence at line 1 column 1

### ISSUE THREAD

**Issue by zhaoziang1626** [ideless/yas-lock#35]
按照教程解锁圣遗物，显示invalid type: map, expected a sequence at line 1 column 1，请问怎么解决？
![image](https://user-images.githubusercontent.com/53320790/221365589-5b9ea8f2-1e51-449d-9a11-e42a0ef6053f.png)

**Comment by ideless** [comment]
看一下lock.json

**Comment by zhaoziang1626** [comment]
![image](https://user-images.githubusercontent.com/53320790/221367724-b2ca6040-1640-4411-818e-23fa4f06aa99.png)
从

**Comment by ideless** [comment]
用最新的[beta](https://github.com/ideless/yas-lock/releases/download/v1.0.9/yas-lock_v1.0.9-beta1.exe)

**Comment by zhaoziang1626** [comment]
好的解决了
