### ISSUE TITLE
不知道是不是因为带鱼屏的原因，一直提示不支持的分辨率

### ISSUE THREAD

**Issue by YiSeHuiiii** [ideless/yas-lock#36]
如图。尝试过重启还是不支持的分辨率。
![6070b7de453579427265b4d33945306](https://user-images.githubusercontent.com/126412056/221426701-bb409f70-50ed-4566-848b-4c20bfbf04b8.png)

**Comment by ideless** [comment]
把原神调成1600*900窗口模式

**Comment by YiSeHuiiii** [comment]
> 把原神调成1600*900窗口模式

用的就是调1600*900的，还试过其他的分辨率都不行

**Comment by ideless** [comment]
原神启动器关掉了吗

**Comment by YiSeHuiiii** [comment]
> 原神启动器关掉了吗

电脑都试过重启了TuT

**Comment by ideless** [comment]
应该有截一张叫test.png的图，发过来看一下

**Comment by YiSeHuiiii** [comment]
> 应该有截一张叫test.png的图，发过来看一下

![test](https://user-images.githubusercontent.com/126412056/221478190-67a757af-ca83-4240-8103-58170824c165.png)

**Comment by ideless** [comment]
我的意思是看一下test.png这张图，正常来讲这张图是程序启动时的游戏截图，我需要看一下这张图的内容来判断哪里出了错。
另外我看到你有yas，用yas会报同样的错吗，还是只有yas-lock这样？

**Comment by YiSeHuiiii** [comment]
> 我的意思是看一下test.png这张图，正常来讲这张图是程序启动时的游戏截图，我需要看一下这张图的内容来判断哪里出了错。 另外我看到你有yas，用yas会报同样的错吗，还是只有yas-lock这样？

上面那个就是test.png的图啊，yas也是这个样子的

**Comment by ideless** [comment]
把文件夹的名字改成别的试试，不要包含原神两个字

**Comment by YiSeHuiiii** [comment]
> 把文件夹的名字改成别的试试，不要包含原神两个字

原来是这样子解决的吗真是太厉害了
