### ISSUE TITLE
给圣遗物加锁去锁没反应

### ISSUE THREAD

**Issue by FujishiroOtone** [ideless/yas-lock#37]
如图所示的提示，请问这是什么问题呢
![{(CKD}EFYLUL63C_QP5_L5Y](https://user-images.githubusercontent.com/19571014/222727808-aa80c3c8-9deb-41ee-8fcc-2da52dcd6cdb.png)

**Comment by ideless** [comment]
你的lock.json是空的

**Comment by FujishiroOtone** [comment]
我后面试了一下，应该是网站导出的json文件有问题，现在解决了
