### ISSUE TITLE
请适配更多分辨率

### ISSUE THREAD

**Issue by Moon-404** [ideless/yas-lock#4]
1.0.3-beta1根据说明只支持1600x900，然而我的设备上只有1600x1200，yas也是支持多个16:9的分辨率，1920x1080无法扫描锁的信息，请适配，谢谢。

**Comment by ideless** [comment]
ok

**Comment by ideless** [comment]
更新到1.0.4试试吧

**Comment by Moon-404** [comment]
已经可以了，感谢。
请问您是否介意我将这个程序与网站的使用方式制作成视频发布在B站等平台上？如果可以的话，需要我标注什么信息呢？

**Comment by ideless** [comment]
不介意，但你可能需要credit一下[yas](https://github.com/wormtql/yas)
