### ISSUE TITLE
--gui打开的网页无法使用，以前好像是正常的

### ISSUE THREAD

**Issue by YuhaoTang** [ideless/yas-lock#42]
点扫描按钮之后卡在这里
![image](https://user-images.githubusercontent.com/15133354/228879696-70e94450-2028-4935-b577-1fac7f1e34cf.png)
控制台报错
![image](https://user-images.githubusercontent.com/15133354/228879870-74294e52-f5e8-43f3-93e9-1de6e5925ca1.png)
![image](https://user-images.githubusercontent.com/15133354/228880012-e981790e-db7a-47b5-9b6f-3cfcca00a0f5.png)
命令行页面（刷新了几次网页）
![image](https://user-images.githubusercontent.com/15133354/228880352-2c89de1b-ebe7-4fb4-a98a-49e561d0dde3.png)

**Comment by ideless** [comment]
现在应该可以了

**Comment by ShadowLyin** [comment]
> 现在应该可以了

好像还是不行。
![image](https://user-images.githubusercontent.com/20549332/229487892-4b4d68ab-d018-460c-b2e9-66246becbeaa.png)

**Comment by ideless** [comment]
忘记更新了，再试试？（还不行就在开发者工具里面禁用缓存

**Comment by ShadowLyin** [comment]
> 忘记更新了，再试试？（还不行就在开发者工具里面禁用缓存

已经可以了
