### ISSUE TITLE
3.6 新圣遗物无法导入Artifact Optimizer

### ISSUE THREAD

**Issue by Given2001** [ideless/yas-lock#44]
![image](https://user-images.githubusercontent.com/60348216/231514091-a1a9805b-e8a8-44d6-af4b-7ac3bfdca798.png)
花海套的SetKey似乎搞错了
![image](https://user-images.githubusercontent.com/60348216/231514382-467c3079-eb2f-462f-9c77-f7e58b5514e5.png)

**Comment by ideless** [comment]
等这条PR：https://github.com/frzyc/genshin-optimizer/pull/1126 的结果吧

**Comment by ideless** [comment]
GO已经改了set key，现在应该可以了

**Comment by Given2001** [comment]
> GO已经改了set key，现在应该可以了

刚试了下，能用了，感谢=。=
