### ISSUE TITLE
ERROR yas::common::utils] 请打开背包圣遗物栏, 按Enter退出

### ISSUE THREAD

**Issue by detesion** [ideless/yas-lock#5]
我已经开了背包还是这样子。。

**Comment by ideless** [comment]
完整的log给我看一下，方便的话最好把游戏截图也发过来（运行yas-lock后自动生成，在dumps文件夹下），可以发我邮箱pyjy@yahoo.com

**Comment by detesion** [comment]
> 完整的log给我看一下，方便的话最好把游戏截图也发过来（运行yas-lock后自动生成，在dumps文件夹下），可以发我邮箱[pyjy@yahoo.com](mailto:pyjy@yahoo.com)

不知道为什么我刚刚开起来运行了一下又可以了，谢谢你。
