### ISSUE TITLE
疑似对1000出头圣遗物数目判断错误

### ISSUE THREAD

**Issue by PrimeZhang** [ideless/yas-lock#53]
在4.0版本后使用yas-lock, 我的圣遗物数目是1003/1800. 扫描过程中会停在圣遗物count=100的地方不再扫描，怀疑是将1000识别为了100并停止扫描。

在命令行加入了yas-lock.exe --number=1000 后程序正常运行。

另一个问题是，readme里并没有给出number等参数的用法，我是读代码猜到使用这个参数的。建议在说明文档里给出这些参数如何使用。

**Comment by Given2001** [comment]
我这边是 `1371/1800` 看程序日志里似乎识别成了 `1371/100`，程序扫描到 `count=137` 就停止了

**Comment by Given2001** [comment]
> 我这边是 `1371/1800` 看程序日志里似乎识别成了 `1371/100`，程序扫描到 `count=137` 就停止了

随便找了个圣遗物升了下级消耗了点狗粮，就正常了

**Comment by Given2001** [comment]
![image](https://github.com/ideless/yas-lock/assets/60348216/b2fdc69b-6534-441e-8083-c268b09c010b)
![image](https://github.com/ideless/yas-lock/assets/60348216/82d6a07a-ab3b-4990-8db4-9279e9b65646)

**Comment by ideless** [comment]
试试[v1.0.12](https://github.com/ideless/yas-lock/releases/tag/v1.0.12)？可能是1500变成1800导致模型识别出错，因为是把识别结果去掉最后5个字母当成数量，所以少识别一个字母就会出现这种情况。不过我这边无论是1.0.11还是1.0.12都没有遇到这个问题。

**Comment by Given2001** [comment]
> 试试[v1.0.12](https://github.com/ideless/yas-lock/releases/tag/v1.0.12)？可能是1500变成1800导致模型识别出错，因为是把识别结果去掉最后5个字母当成数量，所以少识别一个字母就会出现这种情况。不过我这边无论是1.0.11还是1.0.12都没有遇到这个问题。

新版目前没有问题

**Comment by PrimeZhang** [comment]
> 

谢谢。新版已解决此问题。
另外，readme里提到的help用法并不可行。--help命令后会弹出新窗口并迅速自行关闭，并看不到帮助。

**Comment by Given2001** [comment]
> > 
> 
> 谢谢。新版已解决此问题。 另外，readme里提到的help用法并不可行。--help命令后会弹出新窗口并迅速自行关闭，并看不到帮助。

管理员模式终端就可以了吧

**Comment by PrimeZhang** [comment]
> 

啊 多谢。
