### ISSUE TITLE
有一页圣遗物加锁锚点识别错误

### ISSUE THREAD

**Issue by glhfcftm** [ideless/yas-lock#6]
发现有40个本该为加锁状态的圣遗物显示为解锁状态，翻了dumps文件夹发现其中有一页的锚点位置识别错了，原因可能是截图截早了，因为加解锁状态错误的是33个角斗花和7个角斗羽，在背包看了正好是如果正确翻页本应显示的那一页，图2为出错的那一页，图4为我自己在背包截的。
（这次能发现实属碰巧，刚好瞧到了我知道应该为加锁状态的几个，若要每次进行验证也是难以办到的，是否可以在可能出现问题的时候显示提示呢？）

![lock_140 2](https://user-images.githubusercontent.com/24297855/185754859-445fdbc4-42f9-4c96-bf97-46c0a7a01376.png)
![lock_145](https://user-images.githubusercontent.com/24297855/185754880-4dcf218c-bd7d-4d31-8480-2e3a471cea64.png)
![lock_150](https://user-images.githubusercontent.com/24297855/185754886-febaa935-cb42-4707-9111-d0e474f21ded.png)
![截图](https://user-images.githubusercontent.com/24297855/185754887-77975082-bc7b-438a-81dc-9b1169f22a5e.png)

**Comment by glhfcftm** [comment]
补充，又发生了一次，同样也是图片未对准加锁锚点，“截图截早了”的效果，然后重新进行了两轮识别都是正确的。图2为出错的那一页，图1和图3为其前后页，图4为重新识别时的正确结果。（重新识别后，图4代替了图2，图1和图3不变）

![lock_20](https://user-images.githubusercontent.com/24297855/186202520-ec297435-6e40-4ad2-9c03-7f73d6fe6afa.png)
![lock_25](https://user-images.githubusercontent.com/24297855/186202584-9dc4b6d2-0202-404a-b274-6cac75db2e72.png)
![lock_30](https://user-images.githubusercontent.com/24297855/186202608-205f59df-8f38-499b-825e-f7f5c64e0774.png)
![lock_25 (2)](https://user-images.githubusercontent.com/24297855/186202570-5832be3d-b9f8-4aa7-a543-793525f33d0a.png)

**Comment by ideless** [comment]
看上去是游戏卡顿的问题，我想想办法吧

**Comment by ideless** [comment]
试试更新到v1.0.6并调高页面滚动的等待时间到：例如在终端里面输入
```
path/to/yas-lock.exe --scroll-stop 500
```
（意思是调高页面滚动的等待时间为500ms）
或者创建一个快捷方式，在右键“属性”>“目标”里的地址后面加“ --scroll-stop 500”

**Comment by glhfcftm** [comment]
更新了，不过调到1000ms仍然有概率出现同样的问题（图2）。而且仍然是仅仅滚动了一行左右，感觉不一定是等待时间的问题？
![lock_30 2](https://user-images.githubusercontent.com/24297855/192143672-fd09f703-5a6e-46cf-84d6-c19345b7eeab.png)
![lock_35 2](https://user-images.githubusercontent.com/24297855/192143680-5e3a8ce9-62a2-4cc4-a6f6-bc1b08a29619.png)
![lock_40 2](https://user-images.githubusercontent.com/24297855/192143681-ca587970-dce8-4a07-a86f-c3a105af7cee.png)

**Comment by glhfcftm** [comment]
又出现了一种新状况：最后一个圣遗物识别错误，与其同一页的别的都正常（识别结果json如图2所示）。关键是从dumps图片看不出锚点有什么问题，应该是另一种bug？

![lock_183 2](https://user-images.githubusercontent.com/24297855/193508389-5d5fee46-6f25-49cb-84be-d9aa7ccbf5fb.png)
![](https://user-images.githubusercontent.com/24297855/193508426-9638e353-f2a9-493f-9b9a-a172bb49af17.jpg)

**Comment by ideless** [comment]
方便加个qq吗
邮件联系：pyjy@yahoo.com
