### ISSUE TITLE
希望能在出现问题时不直接退出而是显示错误信息

### ISSUE THREAD

**Issue by glhfcftm** [ideless/yas-lock#7]
我发现在出现某些类问题的时候程序会直接退出，用户可能需要猜测出错的原因，也很容易误以为识别正常结束了，是否可以不直接退出而是显示错误信息呢？
目前已知情形：1、游戏卡顿（此时程序连续报数个识别重复圣遗物的warning然后闪退）

**Comment by ideless** [comment]
已在v1.0.6中修复
