### ISSUE TITLE
速度选项该怎么启用？

### ISSUE THREAD

**Issue by CUZNIL** [ideless/yas-lock#9]
我尝试了在文件名后添加--speed 1，也尝试了在启动后的询问是否加解锁界面添加--speed 1也无效
最后是通过在文件夹下运行cmd，在这里面再运行yas-lock才解决的
.\yas-lock.exe --speed 1
但是这个启用流程太麻烦了 如果没有其他方式的话请问可以添加一个txt文件从里面调取设定吗

**Comment by EFrostBlade** [comment]
> 

![图片](https://user-images.githubusercontent.com/34298478/188261265-eaecc8a0-f239-4f2a-9119-b69b556743c4.png)
创建快捷方式并这样设置即可

**Comment by CUZNIL** [comment]
谢谢 是我猪鼻了hhh
